config/routes.rb
Blog::Application.routes.draw do
  
  root :to => "account#start"

  get "account/start"

  get "account/new"

  get "account/remove"

  get "account/login"

  get "account/logout"

  resources :categories

  resources :users

  get "comments/create"

  get "comments/destroy"

  resources :posts do
    resources :comments
  end

  root :to => "account#start"

  post "account/new" => "account#new"

  post "account/login" => "account#login"

end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name, :description
  validates :name, :presence => true, :length => { :minimum => 4, :maximum => 100 }
  validates :description, :presence => true, :length => { :minimum => 20, :maximum => 1000 }
  validates_uniqueness_of :name
  has_many :posts
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :body, :post_id, :user_id
  validates :body, :presence => true, :length => { :minimum => 10, :maximum => 200 }
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :body, :title, :category_id, :user_id
  validates :body, :presence => true, :length => { :minimum => 20, :maximum => 1000 }
  validates :title, :presence => true, :length => { :minimum => 4, :maximum => 100 }
  validates_uniqueness_of :title
  belongs_to :categories
  belongs_to :user
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  # GET /categories
  # GET /categories.json
  def index
    if session[:user_id]
      @categories = Category.all

      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @categories }
      end
    else
      redirect_to :controller => 'account', :action => 'login'
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    if session[:user_id]
      @category = Category.find(params[:id])

      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @category }
      end
    else
      redirect_to :controller => 'account', :action => 'login'
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    if session[:user_id]
      @category = Category.new

      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @category }
      end
    else
      redirect_to :controller => 'account', :action => 'login'
    end
  end

  # GET /categories/1/edit
  def edit
    if session[:user_id]
      @category = Category.find(params[:id])
    else
      redirect_to :controller => 'account', :action => 'login'
    end
  end

  # POST /categories
  # POST /categories.json
  def create
    if session[:user_id]
      @category = Category.new(params[:category])

      respond_to do |format|
        if @category.save
          format.html { redirect_to @category, notice: 'Category was successfully created.' }
          format.json { render json: @category, status: :created, location: @category }
        else
          format.html { render action: "new" }
          format.json { render json: @category.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to :controller => 'account', :action => 'login'
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    if session[:user_id]
      @category = Category.find(params[:id])

      respond_to do |format|
        if @category.update_attributes(params[:category])
          format.html { redirect_to @category, notice: 'Category was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @category.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    if session[:user_id]
      @category = Category.find(params[:id])
      @category.posts.each do |post|
        post.destroy
      end
      @category.destroy

      respond_to do |format|
        format.html { redirect_to categories_url }
        format.json { head :no_content }
      end
    else
      redirect_to :controller => 'account', :action => 'login'
    end
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
  	@post = Post.find(params[:post_id])
  	@comment = @post.comments.build(params[:comment])
  	respond_to do |format|
      if @comment.save
        format.html { redirect_to @post, :notice => 'Komentarz dodany' }
      else
        format.html { render "posts/show" }
      end
    end
  end

  def destroy
  	@comment = Comment.find(params[:id])
  	@comment.destroy

	redirect_to @comment.post  	
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # GET /posts
  # GET /posts.json
  def index
    if session[:user_id]
      @posts = Post.all

      respond_to do |format|
        format.html # index.html.erb
        format.json { render json: @posts }
      end
    else
      redirect_to :controller => 'account', :action => 'login'
    end
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    if session[:user_id]
      @post = Post.find(params[:id])

      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @post }
      end
    else
      redirect_to :controller => 'account', :action => 'login'
    end
  end

  # GET /posts/new
  # GET /posts/new.json
  def new
    if session[:user_id]
      @post = Post.new

      respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @post }
      end
    else
      redirect_to :controller => 'account', :action => 'login'
    end
  end

  # GET /posts/1/edit
  def edit
    if session[:user_id]
      @post = Post.find(params[:id])
    else
      redirect_to :controller => 'account', :action => 'login'
    end
  end

  # POST /posts
  # POST /posts.json
  def create
    if session[:user_id]
      @post = Post.new(params[:post])

      respond_to do |format|
        if @post.save
          format.html { redirect_to @post, notice: 'Post was successfully created.' }
          format.json { render json: @post, status: :created, location: @post }
        else
          format.html { render action: "new" }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to :controller => 'account', :action => 'login'
    end
  end

  # PUT /posts/1
  # PUT /posts/1.json
  def update
    if session[:user_id]
      @post = Post.find(params[:id])

      respond_to do |format|
        if @post.update_attributes(params[:post])
          format.html { redirect_to @post, notice: 'Post was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @post.errors, status: :unprocessable_entity }
        end
      end
    else
      redirect_to :controller => 'account', :action => 'login'
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    if session[:user_id]
      @post = Post.find(params[:id])
      @post.comments.each do |x|
        x.destroy
      end
      @post.destroy

      respond_to do |format|
        format.html { redirect_to posts_url }
        format.json { head :no_content }
      end
    else
      redirect_to :controller => 'account', :action => 'login'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/categories/_form.html.erb
<%= form_for(@category) do |f| %>
  <% if @category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% @category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<h1>Editing category</h1>

<%= render 'form' %>

<%= link_to 'Show', @category %> |
<%= link_to 'Back', categories_path %>

app/views/categories/index.html.erb
<div style='background-color: red'>
  <b>Welcome, </b> <%= link_to User.find(session[:user_id]).username, '/' %> <%= link_to 'Logout', :controller => 'account', :action => 'logout' %>
  <br><h1>Listning categories</h1><br/></div>
  <div style='background-color: yellow'> <font size='3'><%= link_to "Posts", posts_path %> |
  <%= link_to "Categories", categories_path %></font></div>
<br>
<% @categories.reverse.each do |category| %>
  <div style='background-color: #FFCC99'>
    <table width="100%">
      <tr align="Right"><td align="Left"><font size=4><strong><%= link_to category.name, category %></strong></font> created <%= time_ago_in_words category.created_at %> ago </td>
      </tr>
    </table>

  </div>
  <div style='background-color: #FFFF99'>
    <%= truncate category.description, :length => 300 %>
  </div>
  <hr>
<% end %>

<p>
  <%= link_to "New Category", new_category_path %>
<p>

app/views/categories/new.html.erb
<h1>New category</h1>

<%= render 'form' %>

<%= link_to 'Back', categories_path %>

app/views/categories/show.html.erb
 <div style='background-color: red'> <b>Welcome, </b> <%= link_to User.find(session[:user_id]).username, '/' %> <%= link_to 'Logout', :controller => 'account', :action => 'logout' %></div>
 <div style='background-color: yellow'><font size='3'><%= link_to "Posts", posts_path %> |
  <%= link_to "Categories", categories_path %></font></div>
<br>

<div style='background-color: #FFCC99'>
	<table width=100%>
		<tr align="Right">
			<td align='Left'>
				<font size=4><%= @category.name %></font>
			</td>
			<td algin='Right'>
				<%= link_to 'Back', categories_path %> |
				<%= link_to 'Edit', edit_category_path(@category) %> |
				<%= link_to 'Delete', @category, :method => :delete, :confirm => "Are you sure?"%>
			</td>
		</tr>
	</table>
</div>
<hr>
<table style='float: left' width='50%'>
	<tr><td>
		<font size = 4> Description: </font>
		<div style='background-color: #FFFF99'>
			<font size=2 align='justify'><%= @category.description %></font>
		</div>
	</td></tr>
</table>

<table style="float: left" width="50%">
<% if @category.posts.length > 0 %>
	<font size = 4> Posts list: </font>
	<% @category.posts.each do |post| %>
	<tr><td>
		<div style='background-color: #CCFF99'>
			<strong>Title:</strong> <%= link_to post.title, post %> by <strong><%= post.user.username %></strong> <%= time_ago_in_words post.created_at %> ago
		</div>
		<div style='background-color: #CCFFCC'>
			<strong>Text:</strong> <%= truncate post.body, :length => 100 %>
		</div>
		<hr></td></tr>
	<% end %>
</table>
<% end %>

app/views/comments/create.html.erb
<h1>Comments#create</h1>
<p>Find me in app/views/comments/create.html.erb</p>

app/views/comments/destroy.html.erb
<h1>Comments#destroy</h1>
<p>Find me in app/views/comments/destroy.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<% l = Array.new %>
<% Category.all.each do |x| %>
  <% l << [x.name, x.id] %>
<% end %>

<% User.all.each do |x| %>
  <% if x.id = session[:user_id] %>
    <% @user = x %>
  <% end %>
<% end %>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </div>
  <div class="field">
    <%= f.label :category_id %><br />
    <%= f.select :category_id, options_for_select(l) %> <br />
    <%= f.hidden_field :user_id, :value => @user.id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div style='background-color: red'>
  <b>Welcome, </b> <%= link_to User.find(session[:user_id]).username, '/' %> <%= link_to 'Logout', :controller => 'account', :action => 'logout' %>
  <br><h1> Welcome to my Blog</h1><br/></div>
  <div style='background-color: yellow'><font size='3'><%= link_to "Posts", posts_path %> |
  <%= link_to "Categories", categories_path %></font></div>
<br>
<% @posts.reverse.each do |post| %>
  <div style='background-color: #FFCC99'>
    <table width="100%">
      <tr align="Right"><td align="Left"><font size=4><strong><%= link_to post.title, post %></strong></font> created <%= time_ago_in_words post.created_at %> ago by <%= post.user.username %> (<%= link_to post.comments.length, post %> comments)</td>
        <td align="Right">[<%= link_to Category.find(post.category_id).name, Category.find(post.category_id) %>]</td></tr>
    </table>

  </div>
  <div style='background-color: #FFFF99'>
    <%= post.body %>
  </div>
  <% if post.comments.length > 0 %>
    <table width=40%>
      <tr>
        <td>
          <div style='background-color: #F0F0F0'>
            <strong>Last comment: <%= time_ago_in_words post.comments.last.created_at %> ago </strong>
          </div>
          <div style='background-color: #F8F8F8'>
            <%= post.comments.last.body %>
          </div>
        </td>
      </tr>
    </table>
  <% end %>
  <hr>
<% end %>

<p>
  <%= link_to "New Post", new_post_path %>
<p>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<% if defined? @comment and @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>

      <% @comment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
<% end %>
	<div style='background-color: red'> <b>Welcome, </b> <%= link_to User.find(session[:user_id]).username, '/' %> <%= link_to 'Logout', :controller => 'account', :action => 'logout' %></div>
	<div style='background-color: yellow'><font size='3'><%= link_to "Posts", posts_path %> |
  <%= link_to "Categories", categories_path %></font></div>
<br>
<div style='background-color: #FFCC99'>
	<table width=100%>
		<tr align="Right">
			<td align='Left'>
				<font size=4><%= @post.title %></font>
			</td>
			<td algin='Right'>
				<%= link_to 'Back', posts_path %> |
				<%= link_to 'Edit', edit_post_path(@post) %> |
				<%= link_to 'Delete', @post, :method => :delete, :confirm => "Are you sure?"%>
				<font size=3> [<%=link_to Category.find(@post.category_id).name, Category.find(@post.category_id) %>]</font>
			</td>
		</tr>
	</table>
</div>
<hr>
<div style='background-color: #FFFF99'>
	<font size=2><%= @post.body %></font>
</div>
<div align= 'right'><%= @post.user.username %> </div>
<hr>
<hr>

<h2>Commments</h2>
</table>
<table style="float: left" width='75%'>
<% id_of_post = 0 %>
<% @post.comments.find(:all, :order => :created_at).reverse.each do |comment| %>
	<% id_of_post += 1 %>
	<tr><td>
	<div style='background-color: #CCFF99'>[<%= id_of_post %>] <strong><%= link_to "[X]", [@post,comment], :method => :delete, :confirm => "Are you sure?" %> </strong> <%= time_ago_in_words comment.created_at %> ago</div>
	<div style='background-color: #CCFFCC'><%= comment.body %> </div>
	<hr></td></tr>
<% end %>
</table>

<table style="float:left">
	<tr><td>
<%= form_for [@post, @post.comments.build] do |f| %>
	<%= f.text_area :body %><br/>
	<%= f.hidden_field :user_id, :value => session[:user_id]%>
	<%= f.submit "New Comment" %>
<% end %>
	</td></tr>
</table>